name: Release Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update manifest version
        run: |
          jq --arg v "${{ github.event.inputs.version }}" '.version = $v' src/manifest.json > src/manifest.tmp.json
          mv src/manifest.tmp.json src/manifest.json

      - name: Archive extension
        run: |
          cd src
          zip -r ../qr-plugin.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          files: qr-plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 